token: "tokens/my_discordbot.token"  #path is relative to location of this config file
alert:  #optional
  id: 123456789012345678
info:  #optional
  id: 234567890123456789
verbose:
  id: 345678901234567890
accounting:  #optional
  id: 456789012345678901
  whitelist:  #optional
    - "my_storagenode"
error:  #optional
  id: 567890123456789012
debug:  #optional
  id: 678901234567890123
  blacklist:  #optional
    - "my_systemmonitor"
    - "my_pingdrive"