token: "tokens/my_discordbot.token"  #path is relative to location of this config file
alert:  #optional
  id: 123456789012345678
info:  #optional
  id: 234567890123456789
report:  #optional
  id: 345678901234567890
  whitelist:  #optional
    - "my_storagenode"
error:  #optional
  id: 456789012345678901
debug:  #optional
  id: 567890123456789012
  blacklist:  #optional
    - "my_systemmonitor"
    - "my_pingdrive"